import 'package:post_pilot/src/features/jobs/data/models/jobs.dart';
import 'package:post_pilot/src/features/jobs/domain/entities/jobs.dart';

class JobsMapper {
  static JobsEntity toEntity(JobsModel jobs) {
    return JobsEntity(
      key: jobs.key,
      startTime: jobs.startTime,
      endTime: jobs.endTime,
      state: jobs.state,
      jobPriority: jobs.jobPriority,
      specificPriorityValue: jobs.specificPriorityValue,
      resourceOverwrites: jobs.resourceOverwrites,
      source: jobs.source,
      sourceType: jobs.sourceType,
      batchExecutionKey: jobs.batchExecutionKey,
      info: jobs.info,
      creationTime: jobs.creationTime,
      startingScheduleId: jobs.startingScheduleId,
      releaseName: jobs.releaseName,
      type: jobs.type,
      inputArguments: jobs.inputArguments,
      environmentVariables: jobs.environmentVariables,
      outputArguments: jobs.outputArguments,
      hostMachineName: jobs.hostMachineName,
      hasMediaRecorded: jobs.hasMediaRecorded,
      hasVideoRecorded: jobs.hasVideoRecorded,
      persistenceId: jobs.persistenceId,
      resumeVersion: jobs.resumeVersion,
      stopStrategy: jobs.stopStrategy,
      customRuntimeType: jobs.customRuntimeType,
      requiresUserInteraction: jobs.requiresUserInteraction,
      releaseVersionId: jobs.releaseVersionId,
      entryPointPath: jobs.entryPointPath,
      organizationUnitId: jobs.organizationUnitId,
      organizationUnitFullyQualifiedName:
          jobs.organizationUnitFullyQualifiedName,
      reference: jobs.reference,
      processType: jobs.processType,
      profilingOptions: jobs.profilingOptions,
      resumeOnSameContext: jobs.resumeOnSameContext,
      localSystemAccount: jobs.localSystemAccount,
      orchestratorUserIdentity: jobs.orchestratorUserIdentity,
      remoteControlAccess: jobs.remoteControlAccess,
      startingTriggerId: jobs.startingTriggerId,
      maxExpectedRunningTimeSeconds: jobs.maxExpectedRunningTimeSeconds,
      serverlessJobType: jobs.serverlessJobType,
      parentJobKey: jobs.parentJobKey,
      resumeTime: jobs.resumeTime,
      lastModificationTime: jobs.lastModificationTime,
      errorCode: jobs.errorCode,
      fpsProperties: jobs.fpsProperties,
      traceId: jobs.traceId,
      parentSpanId: jobs.parentSpanId,
      projectKey: jobs.projectKey,
      creatorUserKey: jobs.creatorUserKey,
      parentOperationId: jobs.parentOperationId,
      enableAutopilotHealing: jobs.enableAutopilotHealing,
      fpsContext: jobs.fpsContext,
      autoHealStatus: jobs.autoHealStatus,
      id: jobs.id,
      jobError: jobs.jobError,
      autopilotForRobots: jobs.autopilotForRobots,
    );
  }
}
